services:
  nginx:
    build: 
      context: ./requirements/nginx/
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: nginx
    image: nginx:inception
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
  
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    image: mariadb:inception
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception
    restart: always
  
  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpress:inception
    volumes:
      - wordpress_data:/var/www/html/wordpress
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: mariadb
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    secrets:
      - db_password
      - credentials
    networks:
      - inception
    restart: always
  
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/mariadb
  
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/wordpress

networks:
  inception:
    driver: bridge

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt