CREATE DATABASE IF NOT EXISTS __DB_NAME__;
CREATE USER IF NOT EXISTS '__DB_USER__'@'%' IDENTIFIED BY '__DB_PASSWORD__';
GRANT ALL PRIVILEGES ON __DB_NAME__.* TO '__DB_USER__'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY '__DB_ROOT_PASSWORD__';
FLUSH PRIVILEGES;