FROM debian:bookworm

RUN	apt-get update \
		&& apt-get install -y --no-install-recommends nginx openssl \
		&& rm -rf /var/lib/apt/lists/*

ARG DOMAIN_NAME
RUN mkdir -p /etc/nginx/ssl \
	&& openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
	-keyout /etc/nginx/ssl/nginx.key \
	-out /etc/nginx/ssl/nginx.crt \
	-subj "/C=JP/ST=Tokyo/L=Tokyo/O=42/OU=42tokyo/CN=${DOMAIN_NAME}"

COPY conf/nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
